import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.getByRole('heading', { name: 'Multi-step Form' }).click();
  await page.getByText('A three-step wizard with a').click();
  await page.getByText('1').click();
  await page.getByText('2').click();
  await page.getByText('3').click();
  await page.getByText('Personal Info').click();
  await page.getByText('Address').click();
  await page.getByText('Review & Submit').click();
  await page.locator('#progress-step-1').click();
  await page.locator('#progress-step-2').click();
  await page.getByText('First name*').click();
  await page.getByText('Last name*').click();
  await page.getByText('Email*').click();
  await page.getByRole('button', { name: 'Next' }).click();
  await page.locator('#toast-error').click();
  await page.getByText('First name is required.').click();
  await page.getByText('Last name is required.').click();
  await page.getByText('Email is required.').click();
  await page.getByRole('textbox', { name: 'First name' }).fill('Jane');
  await page.getByRole('textbox', { name: 'Last name' }).fill('Doe');
  await page.getByRole('textbox', { name: 'Email' }).fill('janedoe@example.com');
  await page.getByRole('button', { name: 'Next' }).click();
  await page.locator('.lucide.lucide-check').click();
  await page.locator('#progress-step-1').click();
  await page.getByText('2').click();
  await page.getByText('Address', { exact: true }).click();
  await page.getByText('Street address*').click();
  await page.getByText('City*').click();
  await page.getByText('ZIP / Postal code*').click();
  await page.getByRole('button', { name: 'Next' }).click();
  await page.locator('#toast-error').click();
  await page.getByText('Street address is required.').click();
  await page.getByText('City is required.').click();
  await page.getByText('ZIP / postal code is required.').click();
  await page.getByRole('textbox', { name: 'Street address' }).fill('No.105/2, ABCD street, DEF main road, XYZ');
  await page.getByRole('textbox', { name: 'City' }).fill('QWERTY City');
  await page.getByRole('textbox', { name: 'ZIP / Postal code' }).fill('809000');
  await page.getByRole('button', { name: 'Next' }).click();
  await page.locator('#progress-step-2 > .flex.flex-col > .flex > .lucide').click();
  await page.locator('.lucide.lucide-check').first().click();
  await page.getByText('3').click();
  await page.getByRole('heading', { name: 'Review your details' }).click();
  await page.getByText('First name').click();
  await page.getByText('Jane', { exact: true }).click();
  await page.getByText('Last name').click();
  await page.getByText('Doe', { exact: true }).click();
  await page.getByText('Email').click();
  await page.getByText('janedoe@example.com').click();
  await page.getByText('Street', { exact: true }).click();
  await page.getByText('No.105/2, ABCD street, DEF').click();
  await page.getByText('City', { exact: true }).click();
  await page.getByText('QWERTY City').click();
  await page.getByText('ZIP').click();
  await page.getByText('809000').click();
  await page.getByRole('button', { name: 'Back' }).click();
  await page.getByRole('button', { name: 'Next' }).click();
  await page.getByRole('button', { name: 'Submit' }).click();
  await page.locator('#toast-success').click();
  await page.locator('#progress-step-3 > .flex.flex-col > .flex > .lucide').click();
  await page.getByText('All done!Thanks, Jane. Your details were submitted.Start over').click();
  await page.getByRole('heading', { name: 'All done!' }).click();
  await page.getByText('Thanks, Jane. Your details').click();
  await page.getByRole('button', { name: 'Start over' }).click();
});